{% set name = "catkin_tools" %}
{% set version = "0.6.0" %}
{% set sha256 = "ada28d319332632a8a6eb3298df53b7244d89ec5ce532cb747ff3fa7e166bd0f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/catkin/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - remove_trollius.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [win]

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - catkin_pkg >0.2.9
    - pyyaml
    - psutil
    - osrf_pycommon >0.1.1
    - trollius  # [py < 34]

test:
  commands:
    - catkin --help
    - catkin init --help
    - catkin build --help
    - catkin list --help
    - catkin env --help
about:
  home: https://catkin-tools.readthedocs.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: This Python package provides command line tools for working with the catkin meta-buildsystem and catkin workspaces.
  dev_url: https://github.com/catkin/catkin_tools

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
