travis:
  secure:
    BINSTAR_TOKEN: 2mSweH6BsLjCnSZBmNK94+xxlVg6BW2POIDlDzD+2Oxqot486zcPt05JBi+39yMbq3ExL012nz9EfnAGt6QRtygiUHD+SVYPjGxzLzqgeIx29VoxSfslI9Ax9EBfEH1cb6WBk7vKQ3H4VpMfT/Hlk8XIhBi5hm2M3igwO5qSsohb5fieWdVFaoUN9Ard5tmRDjXSK865Z57pdjy73O3ZCdo8B/SRhkuokIYiob9EQQW/frlVibuNvlKn3lvnkaVyKX/bueIajDnv+uzLOImc0WqYmtMQTufcRZhtDCSCrJQ2NAsZAQ3OMVGfl7iWh8FzdnKUf7+fV7kGUK0uoyQgcplLBZzlhW9noNfEmeM/llB6wR5mu8/OWQJHrv8nCNux904X6jL5ZNpxuSKP83mXZ5fwaSrco5bY/J4ZR0GRm8xLBdRPZkP8RA/wA4rWB1a6TFpIRDyltGL+utsHzFtjChspiq9tgCsGXICSo0k5kiEy12EtAyQdpacKW3fEQjMtC8Y+uxpYd+MiQ9G3pol6x+14Yi81lxtYg0qMxOIpJ/uAIEp8j97XiN/BxHAXa+7KuPWZYcFdyvcQM+nEw93UhU0iiLVog/aADJ9mWsGoJVSEi7fNZrSIH4tjxy3NhQueucnmXcqLH7YLXD+xOAE/WDUGmYXla3121i/7RIBZfmY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
